version: "3"

services:
  server:
    build: ./
    environment:
      - DB_HOST=db:5432
      - DB_NAME=pogomap
      - DB_USER=postgres
      - DB_PASS=NjNXFh2XVJgsBY36
    restart: always
    ports:
      - "127.0.0.1:5775:5775/tcp"
    volumes:
      - /srv/pogomap/map/layers:/app/static/layers
    depends_on:
      - db
  db:
    image: mdillon/postgis:11-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=NjNXFh2XVJgsBY36
      - POSTGRES_DB=pogomap
    volumes:
      - /srv/pogomap/db:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
